python -m dr.main \
	--weighted='True' \
	--py1y0=0.9 \
	--random_seed=0 \
	--alg_step='None' \
	--data_dir /nfs/turbo/coe-soto/mmakar/multiple_shortcut/dr/ \
	--exp_dir /nfs/turbo/coe-soto/mmakar/multiple_shortcut/dr/tuning/temp \
	--checkpoint_dir /scratch/mmakar_root/mmakar0/multiple_shortcut/dr/tuning/temp \
	--architecture='pretrained_inception' \
	--training_steps=10 \
	--pixel=299 \
	--batch_size=64 \
	--alpha=0.0 \
	--sigma=10.0 \
	--conditional_hsic='False' \
	--l2_penalty=0.0 \
	--embedding_dim=-1 \
 --gpuid $CUDA_VISIBLE_DEVICES
